#!/usr/bin/env python
"""Parse and prioritize local AI-finance paper radar markdown files."""

from __future__ import annotations

import re
from pathlib import Path

import pandas as pd


TITLE_RE = re.compile(r"^### \[(?P<title>.+?)\]\((?P<url>.+?)\)")
DATE_AUTHOR_RE = re.compile(r"\*\*日期\*\*: (?P<date>.+?) \| \*\*作者\*\*: (?P<authors>.+)")
TAG_RE = re.compile(r"`([^`]+)`")


def parse_topic_markdown(path: str | Path) -> pd.DataFrame:
    """Parse a topic markdown file generated by the local arXiv radar."""
    path = Path(path)
    lines = path.read_text(encoding="utf-8").splitlines()
    rows = []
    current: dict[str, object] | None = None
    summary_lines: list[str] = []
    topic = path.stem

    def flush() -> None:
        nonlocal current, summary_lines
        if current is None:
            return
        current["summary"] = " ".join(line.strip() for line in summary_lines if line.strip())
        rows.append(current)
        current = None
        summary_lines = []

    for line in lines:
        title_match = TITLE_RE.match(line)
        if title_match:
            flush()
            current = {
                "topic": topic,
                "title": title_match.group("title"),
                "url": title_match.group("url"),
            }
            continue
        if current is None:
            continue
        date_match = DATE_AUTHOR_RE.search(line)
        if date_match:
            current["date"] = date_match.group("date")
            current["authors"] = date_match.group("authors")
            continue
        if line.startswith("**标签**"):
            current["tags"] = TAG_RE.findall(line)
            continue
        if line.strip() and line.strip() != "---":
            summary_lines.append(line)
    flush()
    df = pd.DataFrame(rows)
    if df.empty:
        return pd.DataFrame(columns=["topic", "title", "url", "date", "authors", "tags", "summary"])
    df["date"] = pd.to_datetime(df.get("date"), errors="coerce")
    df["tags"] = df["tags"].apply(lambda value: value if isinstance(value, list) else [])
    return df


def load_topic_markdowns(paths: list[str | Path]) -> pd.DataFrame:
    """Load and combine multiple topic markdown files."""
    frames = [parse_topic_markdown(path) for path in paths]
    if not frames:
        return pd.DataFrame()
    return pd.concat(frames, ignore_index=True)


def tag_counts(papers: pd.DataFrame) -> pd.DataFrame:
    """Count tags in a parsed paper table."""
    if papers.empty:
        return pd.DataFrame(columns=["tag", "count"])
    exploded = papers.explode("tags")
    return exploded["tags"].value_counts().rename_axis("tag").reset_index(name="count")


def classify_portfolio_risk_theme(title: str, summary: str, tags: list[str]) -> str:
    """Map a portfolio-risk paper to a practical research bucket."""
    text = f"{title} {summary} {' '.join(tags)}".lower()
    if any(key in text for key in ["wasserstein", "robust", "ambiguity", "distribution"]):
        return "robust_optimization"
    if any(key in text for key in ["cvar", "var", "tail", "extreme", "rvar", "drawdown"]):
        return "tail_risk"
    if any(key in text for key in ["graph", "network", "correlation", "defi", "exposure"]):
        return "network_risk"
    if any(key in text for key in ["reinforcement", "ppo", "policy", "actor", "g-learning"]):
        return "reinforcement_learning"
    if any(key in text for key in ["option", "hedg", "arbitrage", "signature"]):
        return "derivatives_hedging"
    if any(key in text for key in ["black-litterman", "mean-variance", "portfolio optimization"]):
        return "portfolio_construction"
    if any(key in text for key in ["llm", "ai", "governance", "compliance", "deception"]):
        return "ai_governance_risk"
    return "other"


def add_theme_bucket(papers: pd.DataFrame) -> pd.DataFrame:
    """Attach practical theme buckets to parsed papers."""
    out = papers.copy()
    out["theme_bucket"] = [
        classify_portfolio_risk_theme(row.title, row.summary, row.tags)
        for row in out.itertuples(index=False)
    ]
    return out


def prioritize_papers(
    papers: pd.DataFrame,
    preferred_tags: set[str] | None = None,
    preferred_keywords: set[str] | None = None,
    recency_weight: float = 0.25,
) -> pd.DataFrame:
    """Rank papers for follow-up replication or deeper reading."""
    if papers.empty:
        return papers.copy()
    preferred_tags = preferred_tags or {"Factor Mining", "Portfolio Optimization", "Risk Management", "Benchmark"}
    preferred_keywords = preferred_keywords or {
        "a股",
        "alpha",
        "overfit",
        "robust",
        "transaction",
        "cvar",
        "factor",
        "benchmark",
    }
    out = papers.copy()
    max_date = out["date"].max()
    if pd.isna(max_date):
        out["recency_score"] = 0.0
    else:
        age_days = (max_date - out["date"]).dt.days.fillna(365)
        out["recency_score"] = 1.0 / (1.0 + age_days / 30.0)
    out["tag_score"] = out["tags"].apply(lambda tags: len(set(tags) & preferred_tags))
    out["keyword_score"] = out.apply(
        lambda row: sum(
            1
            for keyword in preferred_keywords
            if keyword.lower() in f"{row.title} {row.summary}".lower()
        ),
        axis=1,
    )
    out["priority_score"] = out["tag_score"] + out["keyword_score"] + recency_weight * out["recency_score"]
    return out.sort_values(["priority_score", "date"], ascending=[False, False]).reset_index(drop=True)


def build_watchlist(
    papers: pd.DataFrame,
    min_priority: float = 2.0,
    max_rows: int = 20,
) -> pd.DataFrame:
    """Build a compact watchlist from prioritized papers."""
    ranked = prioritize_papers(papers)
    cols = ["topic", "date", "title", "url", "tags", "theme_bucket", "priority_score"]
    if "theme_bucket" not in ranked.columns:
        ranked = add_theme_bucket(ranked)
    return ranked.loc[ranked["priority_score"] >= min_priority, cols].head(max_rows)


def topic_overview(papers: pd.DataFrame) -> pd.DataFrame:
    """Summarize counts and date ranges by topic."""
    if papers.empty:
        return pd.DataFrame(columns=["topic", "count", "start_date", "end_date"])
    return (
        papers.groupby("topic")
        .agg(count=("title", "count"), start_date=("date", "min"), end_date=("date", "max"))
        .reset_index()
    )
