#!/usr/bin/env python
"""Experiment ledger and promotion rules for the factor factory."""

from __future__ import annotations

import argparse
from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np
import pandas as pd
from pandas.errors import EmptyDataError


@dataclass(frozen=True)
class PromotionThresholds:
    min_selected_factors: int = 10
    min_families: int = 3
    min_periods: int = 24
    min_sharpe: float = 0.50
    min_sortino: float = 0.60
    max_drawdown_floor: float = -0.30
    min_win_rate: float = 0.45
    max_availability_violation_rate: float = 0.0


def _read_csv(output_dir: str | Path, name: str) -> pd.DataFrame:
    path = Path(output_dir) / name
    if not path.exists():
        return pd.DataFrame()
    try:
        return pd.read_csv(path, encoding="utf-8-sig")
    except EmptyDataError:
        return pd.DataFrame()


def load_run_outputs(output_dir: str | Path) -> dict[str, pd.DataFrame]:
    """Load standard tables generated by factor_factory_runner.py."""
    names = [
        "meta.csv",
        "performance.csv",
        "walk_forward_performance.csv",
        "availability_audit.csv",
        "selected.csv",
        "quality.csv",
        "turnover.csv",
        "walk_forward_returns.csv",
    ]
    return {name.removesuffix(".csv"): _read_csv(output_dir, name) for name in names}


def _metric(performance: pd.DataFrame, metric: str) -> float:
    if performance.empty:
        return float("nan")
    if {"metric", "value"}.issubset(performance.columns):
        row = performance.loc[performance["metric"] == metric, "value"]
        return float(row.iloc[0]) if not row.empty else float("nan")
    if {"metric", "net"}.issubset(performance.columns):
        row = performance.loc[performance["metric"] == metric, "net"]
        return float(row.iloc[0]) if not row.empty else float("nan")
    if metric in performance.columns:
        return float(performance[metric].iloc[0])
    return float("nan")


def _meta(meta: pd.DataFrame, field: str) -> float:
    if meta.empty or field not in meta.columns:
        return float("nan")
    return float(meta[field].iloc[0])


def summarize_run(output_dir: str | Path) -> pd.Series:
    """Summarize a factor-factory output directory into one ledger row."""
    tables = load_run_outputs(output_dir)
    perf = tables["performance"]
    if perf.empty:
        perf = tables["walk_forward_performance"]
    meta = tables["meta"]
    audit = tables["availability_audit"]
    selected = tables["selected"]
    quality = tables["quality"]
    turnover = tables["turnover"]
    violation_rate = 0.0
    if not audit.empty and "violation_rate" in audit.columns:
        violation_rate = float(pd.to_numeric(audit["violation_rate"], errors="coerce").fillna(0.0).max())
    avg_selected_quality = np.nan
    if not selected.empty and "quality_score" in selected.columns:
        avg_selected_quality = float(pd.to_numeric(selected["quality_score"], errors="coerce").mean())
    avg_turnover = np.nan
    if not turnover.empty and "turnover" in turnover.columns:
        avg_turnover = float(pd.to_numeric(turnover["turnover"], errors="coerce").mean())
    if not selected.empty and "split" in selected.columns and "factor" in selected.columns:
        selected_factors = float(selected.groupby("split")["factor"].nunique().mean())
    else:
        selected_factors = _meta(meta, "selected_factors") if not meta.empty else float(selected.shape[0])
    if not selected.empty and "split" in selected.columns and "family" in selected.columns:
        families = float(selected.groupby("split")["family"].nunique().mean())
    else:
        families = _meta(meta, "families") if not meta.empty else float(selected["family"].nunique()) if "family" in selected else np.nan

    return pd.Series(
        {
            "output_dir": str(Path(output_dir)),
            "n_rows": _meta(meta, "n_rows"),
            "n_assets": _meta(meta, "n_assets"),
            "n_dates": _meta(meta, "n_dates"),
            "registered_factors": _meta(meta, "registered_factors"),
            "selected_factors": selected_factors,
            "families": families,
            "annual_return": _metric(perf, "annual_return"),
            "annual_volatility": _metric(perf, "annual_volatility"),
            "sharpe": _metric(perf, "sharpe"),
            "sortino": _metric(perf, "sortino"),
            "max_drawdown": _metric(perf, "max_drawdown"),
            "calmar": _metric(perf, "calmar"),
            "win_rate": _metric(perf, "win_rate"),
            "periods": _metric(perf, "periods"),
            "availability_violation_rate": violation_rate,
            "avg_selected_quality": avg_selected_quality,
            "avg_turnover": avg_turnover,
            "quality_rows": int(quality.shape[0]),
        }
    )


def promotion_decision(summary: pd.Series, thresholds: PromotionThresholds = PromotionThresholds()) -> pd.Series:
    """Decide whether a run should be promoted, revised, or rejected."""
    checks = {
        "selected_factors": summary.get("selected_factors", np.nan) >= thresholds.min_selected_factors,
        "families": summary.get("families", np.nan) >= thresholds.min_families,
        "periods": summary.get("periods", np.nan) >= thresholds.min_periods,
        "sharpe": summary.get("sharpe", np.nan) >= thresholds.min_sharpe,
        "sortino": summary.get("sortino", np.nan) >= thresholds.min_sortino,
        "max_drawdown": summary.get("max_drawdown", np.nan) >= thresholds.max_drawdown_floor,
        "win_rate": summary.get("win_rate", np.nan) >= thresholds.min_win_rate,
        "availability": summary.get("availability_violation_rate", np.nan) <= thresholds.max_availability_violation_rate,
    }
    failed = [name for name, ok in checks.items() if not bool(ok)]
    if not failed:
        decision = "promote_to_paper"
    elif {"availability", "periods"} & set(failed):
        decision = "reject_until_data_fixed"
    else:
        decision = "revise_and_rerun"
    return pd.Series(
        {
            "decision": decision,
            "failed_gates": "|".join(failed),
            **{f"gate_{name}": bool(ok) for name, ok in checks.items()},
        }
    )


def append_ledger(
    ledger_path: str | Path,
    output_dir: str | Path,
    experiment_id: str,
    hypothesis: str,
    thresholds: PromotionThresholds = PromotionThresholds(),
) -> pd.DataFrame:
    """Append one run to the experiment ledger."""
    summary = summarize_run(output_dir)
    decision = promotion_decision(summary, thresholds)
    row = pd.concat(
        [
            pd.Series({"experiment_id": experiment_id, "hypothesis": hypothesis, "recorded_at": pd.Timestamp.now().isoformat()}),
            summary,
            decision,
        ]
    ).to_frame().T
    path = Path(ledger_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        ledger = pd.read_csv(path, encoding="utf-8-sig")
        ledger = pd.concat([ledger, row], ignore_index=True)
    else:
        ledger = row
    ledger.to_csv(path, index=False, encoding="utf-8-sig")
    return ledger


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--ledger", required=True)
    parser.add_argument("--experiment-id", required=True)
    parser.add_argument("--hypothesis", required=True)
    args = parser.parse_args()
    ledger = append_ledger(args.ledger, args.output_dir, args.experiment_id, args.hypothesis)
    print(ledger.tail(1).T)


if __name__ == "__main__":
    main()
